### ISSUE TITLE
which version should the `finetuner` module be? 

### ISSUE THREAD

**Issue by elenacliu** [jina-ai/executor-3d-encoder#13]
I was preparing the environment of this repo. However, I found it confused that the python import code in `finetune.py` gives error message:

```python
from finetuner.tuner.callback import BestModelCheckpoint
from finetuner.tuner.pytorch.losses import TripletLoss
from finetuner.tuner.pytorch.miner import TripletEasyHardMiner
```

It seems that there's no `finetuner.tuner` in finetuner module but `finetuner.finetuner`. Besides, callback/pytorch is not in `finetuner.finetuner` now.

Now my `finetuner` module installed by running `pip install -U finetuner` is 0.5.0. Is there any solution? Maybe you can freeze the version in requirements.txt.

**Comment by gmastrapas** [comment]
Hey @elenacliu! Thanks for the feedback! Can you try using `finetuner==0.4.1`? We will freeze the requirement on our part

**Comment by elenacliu** [comment]
@gmastrapas Thank you for your quick reply!

**Comment by JoanFM** [comment]
Hey @elenacliu ,

can you make sure it works so that this issue can be closed?

**Comment by elenacliu** [comment]
@JoanFM Yes, I will close it.
