### ISSUE TITLE
In `farthest_point_sample` function, the first centroid sampled is not random.

### ISSUE THREAD

**Issue by elenacliu** [jina-ai/executor-3d-encoder#14]
I'm reading your codes. 

https://github.com/jina-ai/executor-3d-encoder/blob/main/executor/models/modules.py#L75

The randint line is commented, but in the original implementation and the algorithm itself, it should be random? Maybe we can provide a fixed seed if we want to get the same result?

**Comment by numb3r3** [comment]
Based on the codes,  we can see `farthest ` is a temporal variable to record the maximal position latitude. In this case, I think zero initialization should be better than randomness.
