### ISSUE TITLE
update tutorial in finetuner docs

### ISSUE THREAD

**Issue by numb3r3** [jina-ai/executor-3d-encoder#8]
update the tutorial located at https://finetuner.jina.ai/get-started/3d-mesh/

In the `v0.2.0`, the module `models` from moved to `executor/models`

**Comment by numb3r3** [comment]
closed by https://github.com/jina-ai/finetuner/pull/375

**Comment by elenacliu** [comment]
> 

It seems that the page https://finetuner.jina.ai/get-started/3d-mesh/ is not found now. @numb3r3

**Comment by numb3r3** [comment]
@elenacliu good catch. Our finetuner team is upgrading the documentation. I guess this page needs some revision to work with the latest finetuner.  Anyway, we will try our best to bring it back ASAP.
